- name: configuring tomcat8
  hosts: all
  tasks:
    - name: install tomcat8
      apt:
        name: tomcat8
        state: present
    - name: change port 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat8/server.xml
    - name: service restart
      service:
        name: tomcat8
        state: restarted
    - name: checking the servers
      uri:
        url: "{{item}}"
      with_items:
        - 172.31.32.139:9090
        - 172.31.43.160:9090
        - 172.31.45.213:9090       

