- name: Installing applications using loops
  hosts: all
  tasks: 
    - name: installing s/w applications 
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: absent,c: no}
        - {a: openjdk-8-jdk,b: latest,c: no}
        - {a: git,b: present,c: no}
        - {a: firewalld,b: absent,c: yes}


