- name: user creation using host scope variables
  hosts: webserver
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
