- name: install tomcat8
  hosts: all
  vars:
    - a: tomcat8
    - b: present
    - c: no
  tasks:
     - name: install tomcat8
       apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
